### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by ghost** [zokl/homekit-doorman#1]
What is the setup code?

**Comment by zokl** [comment]
You can change it in the main function. 




S pozdravem,
Zbyněk Kocur
-- 
email: zbynek.kocur@fel.cvut.cz
phone: +420 22435 4054
web: http://www.fel.cvut.cz
Department of Telecommunications Engineering
Faculty of Electrical Engineering
Czech Technical University in Prague
Technicka 2
166 27 Praha 6

**Comment by Tao173** [comment]
I don't have the qualifications to build firmware. I used your firmware (bin folder) directly, so I ask you to tell me the configuration password of the firmware under your bin folder.  I will thank you very much.

**Comment by zokl** [comment]
Try 25068301


S pozdravem,
Zbyněk Kocur
-- 
email: zbynek.kocur@fel.cvut.cz
phone: +420 22435 4054
web: http://www.fel.cvut.cz
Department of Telecommunications Engineering
Faculty of Electrical Engineering
Czech Technical University in Prague
Technicka 2
166 27 Praha 6

**Comment by zokl** [comment]
> What is the setup code?

The Setup Code is shown during the boot of the device on the console.
