### ISSUE TITLE
Great Project!

### ISSUE THREAD

**Issue by Jos3phBurns** [zokl/homekit-doorman#4]
Hey Zokl, this is a great project. I've recently started playing with an ESP8266 and flashed your project to a test unit. Using a multimeter on the GPIOs everything appears to be working but I need to make some configuration changes such as modifying the default opening time from 5 to 3 seconds. I see this can be easily tweaked in the config.h file but I'm stuck with rebuilding the BIn file.

So far I've figured out that I can use the esptool.py to convert an .ELF file to .bin but I'm not sure the exact process for generating this first ELF file or which IDE I should use to do this. Can you provide any guidance or links to instructions?

P.s.
I owe you a beer/coffee. Let me know where I can donate.

**Comment by zokl** [comment]
Hello @Jos3phBurns, did you try to use this build environment https://github.com/maximkulkin/esp-homekit-demo/wiki/Build-instructions-ESP8266 ? Whole project is based on https://github.com/pfalcon/esp-open-sdk. It produces bin file which you need for uploading.
